export const symbols = {
  ES_CREATE_CB: Symbol('ES_CREATE_CB'),
  IS_ANCHOR: Symbol('IS_ANCHOR'),
  NONE: Symbol('NONE'),
  SELF_ES: Symbol('SELF_ES'),
  CACHE_NODES: Symbol('CACHE_NODES'),
  IS_COMPONENT: Symbol('IS_COMPONENT'),
  STYLESHEET_SCOPED: Symbol('STYLESHEET_SCOPED'),
  STYLESHEET_ROOT: Symbol('STYLESHEET_ROOT'),
  DISPOSE: Symbol('DISPOSE'),
};
